import UseContext from "../components/context/UseContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

 return (
    <html lang="en">
      <body>
        <UseContext>
          {children}
        </UseContext>
      </body>
    </html>
  )
}
